### ISSUE TITLE
[collapsible_headings] horizontal placement between subheadings and parent headings

### ISSUE THREAD

**Issue by doolingdavid** [ipython-contrib/jupyter_contrib_nbextensions#1007]
Does anyone know of a way to control the horizontal distance between headings.
For example
## heading 2
asdf
asdf
### heading 3

and I want it rendered so that the collapsable heading button for heading 3 is say 2cm to the right of that for heading 1.

**Comment by jcb91** [comment]
apologies for the delay responding, I completely missed this issue!

> I want it rendered so that the collapsible heading button for heading 3 is say 2cm to the right of that for heading 1

This should be possible with a few css rules, adding different margins for each heading level (currently they're all just right aligned, so add more right margin for those you want more to the left). e.g. something like

```css
.collapsible_headings_toggle .h1 { margin-right: 40px; }
.collapsible_headings_toggle .h2 { margin-right: 32px; }
.collapsible_headings_toggle .h3 { margin-right: 24px; }
.collapsible_headings_toggle .h4 { margin-right: 16px; }
.collapsible_headings_toggle .h5 { margin-right: 8px; }
.collapsible_headings_toggle .h6 { margin-right: 0; }
```

should do it for you. You can stick them in a `custom.css` file, or edit the collapsible headings css file. Hope that helps?
