### ISSUE TITLE
Filter notebook by tags in HTML view

### ISSUE THREAD

**Issue by benelot** [ipython-contrib/jupyter_contrib_nbextensions#1214]
Hello again!

Is there a way to search for specific tags and only show the cells that have it? I write fairly extensive notebooks and it would be great sometimes to only show the higher order results, not all the things I have done ever.

If this does not exist yet: If anybody could point me to another extension that adds things to the frontend (preferably a search box) and some hints on how to hide cells or maybe collapse them to a single line, that would be great.

**Comment by jcb91** [comment]
I don't know of any existing implementation of this, but it sounds like a fairly simple thing to do & potentially quite useful. You could look at the [jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) for an example of filtering results based on tags, I guess, though there are likely better examples elsewhere. I can't think offhand of a sensible way to collapse cells to a single line (CodeMirror's likely to get wonky with scrollbars, but maybe not!), But you could easily just add a css class to hide/modify the cell's (or it's contents') display, I guess

**Comment by jcb91** [comment]
perhaps something like 

```css
/* limit input height to fit maximum of two lines */
.cell.collapsed .input .CodeMirror {
    max-height: 44px;
}

/* hide lines after second, plus all content of second line */
.cell.collapsed .input .CodeMirror-line + .CodeMirror-line + .CodeMirror-line,
.cell.collapsed .input .CodeMirror-line + .CodeMirror-line span {
    display: none;
}

/* add a collapsed note to any second input line */
.cell.collapsed .input .CodeMirror-line:first-child + .CodeMirror-line:before {
    content: '... (collapsed) ...';
}
```

in combination with calling `cell.output_area.collpase()`?
