### ISSUE TITLE
Remove metadata from notebooks

### ISSUE THREAD

**Issue by timsainb** [ipython-contrib/jupyter_contrib_nbextensions#1322]
Is there an option to remove the metadata:
```
---
toc:
  base_numbering: 1
  nav_menu: {}
  number_sections: true
  sideBar: true
  skip_h1_title: false
  title_cell: Table of Contents
  title_sidebar: Contents
  toc_cell: false
  toc_position: {}
  toc_section_display: true
  toc_window_display: false
---
```

So that it does not render in the readme.md of Github repos?
